"""Operational metrics — what the system indexed, how fast it answers, how
accurate it is, and what humans said about it.

Everything here is computed from artifacts the system already produces: the
index itself, `fixtures/eval-history.jsonl` (written by `eval --log`), and
the local query and feedback logs. Nothing is estimated and nothing is
generated by a model — if a number is missing it is reported as missing
rather than filled in, because the point of this surface is that the
accuracy claims are checkable.
"""

from __future__ import annotations

import json
import math
import sqlite3
from datetime import datetime
from pathlib import Path

MAX_LOG_LINES = 20_000  # a bounded tail keeps the endpoint cheap on big logs
MAX_LIVE_EVAL_QUESTIONS = 120  # bounds the cost of scoring on every page load


def wilson(successes: int, total: int, z: float = 1.96) -> list[float] | None:
    """95% Wilson score interval for a proportion.

    A rate measured on 13 questions is not the same claim as one measured on
    1,300, and reporting it bare invites exactly the challenge it deserves.
    Wilson (rather than the normal approximation) stays sane at small n and
    near 0% or 100%, which is where small fixture sets actually live.
    """
    if total <= 0:
        return None
    p = successes / total
    denom = 1 + z * z / total
    centre = (p + z * z / (2 * total)) / denom
    margin = z * math.sqrt(p * (1 - p) / total + z * z / (4 * total * total)) / denom
    return [round(max(0.0, centre - margin), 3), round(min(1.0, centre + margin), 3)]


def _parse_ts(value) -> datetime | None:
    try:
        return datetime.fromisoformat(str(value))
    except (TypeError, ValueError):
        return None


def _tail_jsonl(path: Path, limit: int = MAX_LOG_LINES) -> list[dict]:
    if not path.exists():
        return []
    rows: list[dict] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines()[-limit:]:
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue  # torn write; never fatal
        if isinstance(obj, dict):
            rows.append(obj)
    return rows


def _percentile(values: list[float], pct: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    idx = min(len(ordered) - 1, max(0, round((pct / 100) * (len(ordered) - 1))))
    return round(ordered[idx], 1)


def health(conn: sqlite3.Connection) -> dict:
    docs = conn.execute("SELECT COUNT(*) n FROM documents").fetchone()["n"]
    chunks = conn.execute("SELECT COUNT(*) n FROM chunks").fetchone()["n"]
    size = conn.execute("SELECT COALESCE(SUM(size), 0) n FROM documents").fetchone()["n"]
    last = conn.execute("SELECT MAX(indexed_at) t FROM documents").fetchone()["t"]
    by_type = [
        dict(r)
        for r in conn.execute(
            "SELECT filetype, COUNT(*) docs FROM documents "
            "GROUP BY filetype ORDER BY docs DESC, filetype"
        )
    ]
    empty = conn.execute(
        "SELECT COUNT(*) n FROM documents d "
        "WHERE NOT EXISTS (SELECT 1 FROM chunks c WHERE c.doc_id = d.id)"
    ).fetchone()["n"]
    return {
        "documents": docs,
        "chunks": chunks,
        "bytes": size,
        "last_indexed": last,
        "by_type": by_type,
        # A document that produced no chunks is indexed but unsearchable —
        # worth surfacing rather than hiding inside a healthy-looking count.
        "documents_without_chunks": empty,
        "avg_chunks_per_doc": round(chunks / docs, 1) if docs else 0,
    }


def accuracy(history_path: Path, db_name: str | None = None) -> dict:
    """Latest eval run and its trend, straight from the logged history."""
    rows = [r for r in _tail_jsonl(history_path) if "mrr" in r]
    if db_name:
        scoped = [r for r in rows if r.get("db") == db_name]
        # Fall back to every run rather than showing nothing when the active
        # database has never been scored.
        rows = scoped or rows
    if not rows:
        return {"available": False}
    latest = rows[-1]
    total = latest.get("questions") or 0
    series = [
        {
            "ts": r.get("ts", ""),
            "label": r.get("label", ""),
            "hit_at_1": round((r.get("hit_at_1") or 0) / r["questions"], 3) if r.get("questions") else 0,
            "hit_at_k": round((r.get("hit_at_k") or 0) / r["questions"], 3) if r.get("questions") else 0,
            "mrr": r.get("mrr", 0),
        }
        for r in rows[-12:]
    ]
    hit1 = latest.get("hit_at_1") or 0
    hitk = latest.get("hit_at_k") or 0

    # Did the last change help? The eval harness exists to answer exactly
    # this, so the panel should not make the operator diff it by eye.
    delta = None
    if len(rows) > 1:
        prev = rows[-2]
        prev_total = prev.get("questions") or 0
        if prev_total:
            delta = {
                "since": prev.get("label") or prev.get("ts", ""),
                "hit_at_1": round(hit1 / total - (prev.get("hit_at_1") or 0) / prev_total, 3)
                if total else 0,
                "hit_at_k": round(hitk / total - (prev.get("hit_at_k") or 0) / prev_total, 3)
                if total else 0,
                "mrr": round((latest.get("mrr", 0) or 0) - (prev.get("mrr", 0) or 0), 3),
                "comparable": prev.get("fixtures") == latest.get("fixtures"),
            }

    return {
        "available": True,
        "ts": latest.get("ts", ""),
        "label": latest.get("label", ""),
        "fixtures": latest.get("fixtures", ""),
        "db": latest.get("db", ""),
        "questions": total,
        "k": latest.get("k", 5),
        "hit_at_1": round(hit1 / total, 3) if total else 0,
        "hit_at_k": round(hitk / total, 3) if total else 0,
        "hit_at_1_ci": wilson(hit1, total),
        "hit_at_k_ci": wilson(hitk, total),
        "mrr": latest.get("mrr", 0),
        "runs": len(rows),
        "series": series,
        "delta": delta,
    }


def live_accuracy(db_path: Path, fixtures_path: Path | None, k: int = 5) -> dict:
    """Score the CURRENT index against the fixtures, right now.

    The logged history is the published baseline; this is drift detection —
    and, more usefully, it names the questions that are failing *today*,
    which turns a score into a to-do list.
    """
    if not fixtures_path or not fixtures_path.exists():
        return {"available": False, "reason": "no fixture file for this database"}
    try:
        from .evaluate import load_fixtures, run_eval

        fixtures = load_fixtures(fixtures_path)
        if not fixtures:
            return {"available": False, "reason": "fixture file is empty"}
        if len(fixtures) > MAX_LIVE_EVAL_QUESTIONS:
            return {
                "available": False,
                "reason": f"{len(fixtures)} fixtures exceeds the live-scoring limit "
                          f"({MAX_LIVE_EVAL_QUESTIONS}) — run `uplink eval` instead",
            }
        result = run_eval(db_path, fixtures_path, k=k)
    except (OSError, ValueError, sqlite3.Error) as exc:
        return {"available": False, "reason": f"{type(exc).__name__}: {exc}"}

    total = result.total or 0
    failing = [
        {"q": row["q"], "top_path": row.get("top_path", "")}
        for row in result.per_question if not row.get("rank")
    ]
    weak = [
        {"q": row["q"], "rank": row["rank"]}
        for row in result.per_question if row.get("rank", 0) > 1
    ]
    return {
        "available": True,
        "fixtures": fixtures_path.name,
        "questions": total,
        "k": k,
        "hit_at_1": round(result.hit_at_1 / total, 3) if total else 0,
        "hit_at_k": round(result.hit_at_k / total, 3) if total else 0,
        "mrr": round(result.mrr, 3),
        "failing": failing,
        "weak": weak,
    }


def performance(query_log: Path) -> dict:
    rows = _tail_jsonl(query_log)
    searches = [r for r in rows if r.get("kind") != "doc" and "latency_ms" in r]
    opens = [r for r in rows if r.get("kind") == "doc"]
    latencies = [float(r["latency_ms"]) for r in searches if isinstance(r.get("latency_ms"), (int, float))]
    empty = sum(1 for r in searches if not r.get("hits"))
    return {
        "searches": len(searches),
        "source_opens": len(opens),
        "median_ms": _percentile(latencies, 50),
        "p95_ms": _percentile(latencies, 95),
        "zero_hit_rate": round(empty / len(searches), 3) if searches else 0,
        "recent": [
            {"ts": r.get("ts", ""), "latency_ms": r.get("latency_ms"), "hits": r.get("hits", 0)}
            for r in searches[-30:]
        ],
    }


def answers(asks_dir: Path, query_log: Path, notes_path: Path | None = None) -> dict:
    """The generative side — the part that was previously unmeasured.

    Generation is what the product actually does, so it needs its own
    numbers: how long an answer took, how many sources it stood on, and
    whether a human then went and CHECKED one. That last figure —
    verification rate — is the honest measure of whether citations are
    doing their job or just decorating the answer.
    """
    if not asks_dir.is_dir():
        return {"answered": 0}

    opens: list[tuple[str, datetime]] = []
    for row in _tail_jsonl(query_log):
        if row.get("kind") in ("doc", "original") and row.get("path"):
            ts = _parse_ts(row.get("ts"))
            if ts:
                opens.append((str(row["path"]), ts))

    saved_titles = set()
    if notes_path and notes_path.exists():
        for note in _tail_jsonl(notes_path):
            if not note.get("deleted") and note.get("title"):
                saved_titles.add(str(note["title"]).strip().lower())

    answered = 0
    durations: list[float] = []
    citation_counts: list[int] = []
    verified = 0
    uncited = 0
    saved = 0

    for resp_file in sorted(asks_dir.glob("*.response.json")):
        try:
            resp = json.loads(resp_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError, OSError):
            continue
        if not isinstance(resp, dict) or resp.get("state") != "answered":
            continue
        answered += 1

        cites = resp.get("citations") if isinstance(resp.get("citations"), list) else []
        citation_counts.append(len(cites))
        if not cites:
            uncited += 1

        req_file = asks_dir / resp_file.name.replace(".response.json", ".request.json")
        answered_at = _parse_ts(resp.get("ts"))
        if req_file.exists() and answered_at:
            try:
                req = json.loads(req_file.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, UnicodeDecodeError, OSError):
                req = {}
            asked_at = _parse_ts(req.get("ts"))
            if asked_at:
                durations.append(max(0.0, (answered_at - asked_at).total_seconds()))
            question = str(req.get("q", "")).strip().lower()
            if question and question in saved_titles:
                saved += 1

        # Verified = a cited document was opened AFTER the answer landed.
        cited_paths = {
            str(c.get("path")) for c in cites
            if isinstance(c, dict) and c.get("path")
        }
        if cited_paths and answered_at:
            if any(p in cited_paths and ts >= answered_at for p, ts in opens):
                verified += 1

    return {
        "answered": answered,
        "median_seconds": round(sorted(durations)[len(durations) // 2], 1) if durations else None,
        "avg_citations": round(sum(citation_counts) / len(citation_counts), 1)
        if citation_counts else None,
        "uncited_answers": uncited,
        "verified": verified,
        "verification_rate": round(verified / answered, 3) if answered else None,
        "saved_as_notes": saved,
        "save_rate": round(saved / answered, 3) if answered else None,
    }


def feedback_loop(feedback_log: Path, promoted: Path | None = None) -> dict:
    """The human-in-the-loop signal: votes in, fixtures out."""
    rows = _tail_jsonl(feedback_log)
    up = sum(1 for r in rows if r.get("vote") == "up")
    down = sum(1 for r in rows if r.get("vote") == "down")
    by_doc: dict[str, dict] = {}
    for r in rows:
        path = str(r.get("path") or "")
        if not path:
            continue
        entry = by_doc.setdefault(path, {"path": path, "up": 0, "down": 0})
        if r.get("vote") == "up":
            entry["up"] += 1
        elif r.get("vote") == "down":
            entry["down"] += 1
    ranked = sorted(by_doc.values(), key=lambda d: (d["up"] + d["down"]), reverse=True)[:5]
    promoted_count = len(_tail_jsonl(promoted)) if promoted and promoted.exists() else 0
    total = up + down
    return {
        "up": up,
        "down": down,
        "total": total,
        "helpful_rate": round(up / total, 3) if total else None,
        "promoted_fixtures": promoted_count,
        # Upvotes not yet turned into fixtures — the actionable backlog of
        # the self-improvement loop.
        "pending_promotion": max(0, up - promoted_count),
        "by_document": ranked,
    }


def gaps(conn: sqlite3.Connection, query_log: Path, limit: int = 8) -> dict:
    """Where retrieval is failing, and — where possible — why.

    Every search that returned nothing is a question the corpus could not
    answer in the words it was asked. Splitting those queries into terms and
    checking each against the FTS index separates the two very different
    causes: the corpus genuinely lacks the topic, or it holds it under
    different words. The second is fixable, and naming the missing term is
    the actionable half of the self-improvement loop.
    """
    from .search import _STOPWORDS, _WORD_RE

    rows = _tail_jsonl(query_log)
    failed: dict[str, dict] = {}
    for row in rows:
        if row.get("kind") in ("doc", "original"):
            continue
        query = str(row.get("q") or "").strip()
        if not query or row.get("hits"):
            continue
        entry = failed.setdefault(
            query.lower(), {"q": query, "count": 0, "last": row.get("ts", "")}
        )
        entry["count"] += 1
        entry["last"] = row.get("ts", entry["last"])

    zero_hit = sorted(
        failed.values(), key=lambda e: (e["count"], e["last"]), reverse=True
    )[:limit]

    # Which individual terms appear nowhere in the index? A term that matches
    # nothing on its own is the reason its whole query matched nothing.
    unknown: dict[str, dict] = {}
    for entry in failed.values():
        for word in _WORD_RE.findall(entry["q"]):
            token = word.lower()
            if len(token) < 3 or token in _STOPWORDS or token in unknown:
                continue
            try:
                hit = conn.execute(
                    "SELECT 1 FROM chunks_fts WHERE chunks_fts MATCH ? LIMIT 1",
                    (f'"{word}"',),
                ).fetchone()
            except sqlite3.Error:
                continue
            if hit is None:
                unknown[token] = {"term": word, "queries": []}
        for token, info in unknown.items():
            if token in entry["q"].lower() and entry["q"] not in info["queries"]:
                info["queries"].append(entry["q"])

    return {
        "zero_hit": zero_hit,
        "zero_hit_total": len(failed),
        "unknown_terms": sorted(
            unknown.values(), key=lambda u: len(u["queries"]), reverse=True
        )[:limit],
    }


def collect(
    conn: sqlite3.Connection,
    history_path: Path,
    query_log: Path,
    feedback_log: Path,
    promoted: Path | None = None,
    db_name: str | None = None,
    db_path: Path | None = None,
    fixtures_dir: Path | None = None,
    asks_dir: Path | None = None,
    notes_path: Path | None = None,
) -> dict:
    logged = accuracy(history_path, db_name)

    # Score the live index against whichever fixture set this database was
    # last measured with — that is the only fixture file we can honestly
    # claim applies to it.
    live = {"available": False, "reason": "no logged run names a fixture set"}
    if db_path is not None and fixtures_dir is not None and logged.get("fixtures"):
        live = live_accuracy(
            db_path, fixtures_dir / logged["fixtures"], k=logged.get("k", 5)
        )

    return {
        "health": health(conn),
        "accuracy": logged,
        "live": live,
        "performance": performance(query_log),
        "answers": answers(asks_dir, query_log, notes_path) if asks_dir else {"answered": 0},
        "feedback": feedback_loop(feedback_log, promoted),
        "gaps": gaps(conn, query_log),
    }
