"""Opening questions for a collection.

A blank search box tells a new user nothing about what the corpus can
answer, so the empty state offers real starting points. These are derived
deterministically from the index — section titles and document titles — not
generated by a model: the same corpus always yields the same suggestions,
they cost nothing, and they can never suggest something the corpus does not
actually contain.
"""

from __future__ import annotations

import re
import sqlite3

# Extractor-generated section labels that carry no topic ("Page 31",
# "Sheet1", a bare number, or the document's own filename stem).
_NOISE_SECTION = re.compile(
    r"^(page\s*\d+|sheet\s*\d*|table\s*\d*|figure\s*\d*|\d+|[ivxlc]+)$", re.I
)
MAX_SUGGESTIONS = 6


def _useful_section(title: str, doc_titles: set[str]) -> bool:
    t = (title or "").strip()
    if len(t) < 4 or len(t) > 70:
        return False
    if _NOISE_SECTION.match(t):
        return False
    if t.lower() in doc_titles:
        return False
    return bool(re.search(r"[A-Za-z]{3}", t))


def suggestions(conn: sqlite3.Connection, collection: str | None = None) -> list[str]:
    """Up to MAX_SUGGESTIONS opening questions, stable for a given index."""
    where, params = "", []
    if collection:
        where = "WHERE d.collection = ?"
        params = [collection]

    docs = conn.execute(
        f"""
        SELECT d.title, d.path, COUNT(c.id) n
        FROM documents d LEFT JOIN chunks c ON c.doc_id = d.id
        {where}
        GROUP BY d.id ORDER BY n DESC, d.path
        """,
        params,
    ).fetchall()
    if not docs:
        return []
    doc_titles = {str(d["title"] or "").strip().lower() for d in docs}

    sections = conn.execute(
        f"""
        SELECT c.section, COUNT(*) n
        FROM chunks c JOIN documents d ON d.id = c.doc_id
        {where}
        GROUP BY c.section ORDER BY n DESC, c.section
        LIMIT 60
        """,
        params,
    ).fetchall()

    out: list[str] = []
    seen: set[str] = set()

    def add(q: str) -> None:
        key = q.lower()
        if key not in seen and len(out) < MAX_SUGGESTIONS:
            seen.add(key)
            out.append(q)

    # Topic questions first — they show what the corpus is actually about.
    for row in sections:
        if len(out) >= MAX_SUGGESTIONS - 2:
            break
        title = (row["section"] or "").strip()
        if _useful_section(title, doc_titles):
            add(f"What does the documentation say about {title}?")

    # Then per-document prompts, which always work even for PDFs whose only
    # section labels are page numbers.
    for d in docs[:3]:
        name = (d["title"] or d["path"] or "").strip()
        if name:
            add(f"Summarize {name}")

    if collection:
        add(f"What are the main themes across the {collection} collection?")
    else:
        add("What are the main themes across these documents?")
    return out[:MAX_SUGGESTIONS]
